# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('geo_x', models.FloatField()),
                ('geo_y', models.FloatField()),
                ('filling', models.IntegerField(max_length=50)),
            ],
        ),
    ]
