# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('inside_bool', models.BooleanField()),
                ('geo_x', models.IntegerField()),
                ('geo_y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='filling',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='news',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombdata.Object'),
        ),
    ]
