# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bombdata', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('admin', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='object',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='object',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='object',
            name='activity',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.CharField(default='s', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bombdata.Number'),
        ),
    ]
