# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0003_auto_20170304_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
