# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0004_auto_20170304_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='number',
        ),
    ]
