# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0005_remove_object_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='number',
        ),
        migrations.AddField(
            model_name='object',
            name='number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bombdata.Number'),
            preserve_default=False,
        ),
    ]
