# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0006_auto_20170304_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
