# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0008_auto_20170304_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['activity']},
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together=set([('number', 'activity')]),
        ),
    ]
