# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0017_auto_20170304_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='geo_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='geo_y',
            field=models.FloatField(),
        ),
    ]
