# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bombdata', '0018_auto_20170305_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bombdata.UserInfo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bombdata.UserInfo'),
        ),
    ]
